export const SITE_CONFIG = {
  name: "TheHomeVersus",
  tagline: "Transparent Home Product Comparisons",
  description: "Independent product comparisons, buying guides, and practical notes for home, kitchen, pet, and family gear.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://thehomeversus.com",
  ogImage: "/og-image.jpg",
  keywords: [
    "home product comparisons",
    "appliance buying guides",
    "cleaning product reviews",
    "kitchen product comparisons",
    "baby gear comparisons",
    "pet product reviews",
    "editorial buying guides",
    "e-reader reviews",
    "kindle comparisons",
    "kindle paperwhite review",
    "amazon kindle review",
    "kindle paperwhite vs kindle",
    "best kindle for travel",
    "best kindle for reading in bed",
  ],
  publisherId: process.env.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID || "ca-pub-3012411444875177",
  amazonAffiliateDisclosure: "As an Amazon Associate, we earn from qualifying purchases.",
  copyright: `© ${new Date().getFullYear()} TheHomeVersus.com`,
  contactEmail: "cs.nexatech@gmail.com",
  social: {
    facebook: "https://facebook.com/thehomeversus",
    instagram: "https://instagram.com/thehomeversus",
    twitter: "https://twitter.com/thehomeversus",
    youtube: "https://youtube.com/@thehomeversus",
  }
};
